CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(20) UNIQUE,
  password VARCHAR(30)
);

CREATE TABLE tasks (
id SERIAL PRIMARY KEY,
user_id INTEGER,
title CHARACTER VARYING(50),
description CHARACTER VARYING(100),
status CHARACTER VARYING(30),
CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);